analyzer:
  # These are errors when building in Google
  errors:
    unused_import: error
    unused_element: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    - comment_references
    - prefer_typing_uninitialized_variables
